package com.workmotion.hr.statemachine.states;

public interface WorkPermitCheckStates {
    String WORK_PERMIT_CHECK_STARTED = "WORK_PERMIT_CHECK_STARTED";
    String WORK_PERMIT_CHECK_PENDING_VERIFICATION = "WORK_PERMIT_CHECK_PENDING_VERIFICATION";
    String WORK_PERMIT_CHECK_FINISHED = "WORK_PERMIT_CHECK_FINISHED";
}
